# Site settings
title: Your Site Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write a brief description of your site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog-mbktechstudio.netlify.app" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/